### ISSUE TITLE
Segmentation in loaded kzips not always visible even though overlay == true

### ISSUE THREAD

**Issue by my-tien** [knossos-project/knossos#119]
Overlays in this kzip are not displayed: 

https://www.dropbox.com/s/krdms18hmkmm3sc/segmentationJobsfinal_job_257.002.k.zip?dl=0

When having the above kzip in KNOSSOS, loading the following kzip also loads its overlays successfully, but the "unsaved changes" dialog pops up:

https://www.dropbox.com/s/4td1vatvsu9dvv7/segmentationJobsfinal_job_257.k.zip?dl=0

**Comment by Optiligence** [comment]
In your branch Knossos starts with segmentation disabled. 
The first file contains an invalid path and no overlays, so nothing changes. 
At least the case here for the second file is the inability to download the remote conf file (because the http code is extracted after the curl_eh is destroyed), so nothing changes again. 
The unsaved changes are clearing the skeleton or the segmentation while you still have a loaded file and then load a dataset. (related #28)
The dataset may be loaded after the snappy cubes got loaded (the snappy cache is cleared through the `newAnnotationSlot` which is called automatically when there’re no unsaved changes). 
So you’re only ever able to see snappy cubes from the annotation file when dataset loading fails…

**Comment by Optiligence** [comment]
Quick fix would be reloading the annotation after `loadDataset`.

**Comment by Optiligence** [comment]
#127
