### ISSUE TITLE
relax coord paste

### ISSUE THREAD

**Issue by Optiligence** [knossos-project/knossos#173]
accept extra symbols before and after the 3 numbers (i.e. parenthesis) and more?

**Comment by orenshatz** [comment]
Disagree

**Comment by orenshatz** [comment]
Refine:
The relax regexp would be a textual string that the user can override if he likes and he knows what a regexp is.
Otherwise instead of users frustrated with the current de-facto regexp, users would be frustrated with the new regexp - either because it's still tight, or because it's too relaxed.

**Comment by jmrk84** [comment]
There is no too relaxed in our case. Here is the maximal relaxed regex I could get working in Python that solves the issue once and forever.

import re
coord='[[212],[342],4324]'
mobj=re.search(r'\D*(?P<x>\d*)\D*(?P<y>\d*)\D*(?P<z>\d*)\D*', coord)
print mobj.group('x')
print mobj.group('y')
print mobj.group('z')

**Comment by Optiligence** [comment]
I don’t see how the regex example would work properly, but nvmd.
