### ISSUE TITLE
Coordinate not properly restored after erasure

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#304]
Change a coordinate by editing the edit box of a certain axis (e.g. z):
First enter 20 and apply by pressing enter.
Then erase both digits using backspace, and press enter.
As the new empty string is invalid, the user would expect the value restored to 20.
Instead the value is restored to 2.

**Comment by Optiligence** [comment]
It’s because usually values are applied right when you edit them and not only after loosing focus/pressing enter. 
A `CoorectToPreviousFinishedEdit` in `QAbstractSpinBox::CorrectionMode` would be a nice proposal to Qt. 
Although I don’t really agree that this is an issue, I implemented a custom spinbox.
