### ISSUE TITLE
Make segmentation object table sortable

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#323]
It is currently impossible to navigate to specific objects (possibility to jump to a specific object ID would also be nice) etc, this is close to a bug basically.

**Comment by Optiligence** [comment]
You can find the position if the mergelist is already sorted, K will only mix them if you delete objects in the middle.

**Comment by Optiligence** [comment]
The segmentation operations of 
- creating (adding at the end)
- deleting (swap last value into void)
- highlighting (every object retrieved from the hashmap knows its index)

in the table were meant to be constant, which is impossible when you have to sort data. 
And if you enable sorting on the view, the user can only switch between asc and desc order and not to display the data in it’s internal order. 

There seemed to be performance issues especially with highlighting (selecting a random object in the viewport) on a large mergelist (a few 100k objects) when sorting was enabled, which is why I disabled it again. 

I implemented a way for the view to have sorting enabled, but the user to be able to disable it by cycling through the sort orders on the header. 

Maybe I’ll stress test with huge mergelists later, but no one will probably even notice if it’s slower.
