### ISSUE TITLE
boundary box missing in 3d vp snapshot

### ISSUE THREAD

**Issue by Optiligence** [knossos-project/knossos#343]

**Comment by my-tien** [comment]
This is not a bug but intended, because the box clutters the image without any benefit.

**Comment by Optiligence** [comment]
Well it tries to visualize the size of the annotation with respect to the dataset. 
Taking a snapshot doesn’t change that. 
But i can see that this is not always wanted.

**Comment by my-tien** [comment]
You think, there should be an option at least? I think the axis are sufficient for this.

**Comment by Optiligence** [comment]
Or a statement that the boundary box is removed? idk, was just arguing your statement. 
It is at least an observable/irritating difference to what you see in the GUI.

**Comment by my-tien** [comment]
I really don’t think people miss the box when looking at the snapshot. More likely they will close their image manipulation program again, relieved of having to remove it manually ^^
If you need size information, you turn on the axes and rotate the skeleton to your liking.

I say that because I don’t know how I could give a hint in the gui without confusing the user even more. does “show axes (no box)” mean that if I don't check this, I will get a box and no axes?

**Comment by n0void** [comment]
It would be nice if the view would change according to what the snapshot will be, as to reduce the confusion. But ultimately it might be negligible since the potential benefit (from having a nice clean snapshot) outweighs the problem with visual detail during the shot.
