### ISSUE TITLE
Meshes and skeletons cause rendering trouble

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#363]
Severe rendering trouble in 3d VP when both co-exist.

**Comment by my-tien** [comment]
The problem seems to be specific to windows.
If trees and pointcloud exist at the same time, the 3d vp shows this strange artifact in the color of the tree instead of the tree itself:

![pasted image at 2016_10_12 05_38 pm](https://cloud.githubusercontent.com/assets/3898364/19330781/be314b8e-90e0-11e6-8b40-6e039d21cda8.png)

Zooming in and out also influences its appearance.

KNOSSOS also crashes reproducibly in two ways:

Crash 1:
1. Open KNOSSOS
2. Load pointcloud
3. Load skeleton annotation file choosing “override”

Crash 2:
1. Open KNOSSOS
2. In preferences > trees choose “Show only selected trees”
3. Load pointcloud
4. Load 300k skeleton choosing “merge”
5. Switch to “Show whole skeleton”
