### ISSUE TITLE
Nodes are rendered way too small in ortho VPs

### ISSUE THREAD

**Issue by jmrk84** [knossos-project/knossos#364]
... also the snapshot of an ortho vp looks very different from what one can see normally.

**Comment by jmrk84** [comment]
I think it applies only to the former "lines and points" rendering mode

**Comment by Optiligence** [comment]
Did you explicitly select lines and points or did it render in lines and points by accident? 
The former is unfixable because lines and points don’t allow individual sizes. 
The latter would indeed be a bug.

**Comment by Optiligence** [comment]
In lines and points there is/was a default (point) size of 3 screen pixels for all nodes. 
Because we use ortho projections it is possible to scale the size to get bigger when zooming in. 
But since there is only one size for all nodes, it won’t be possible to reflect individual nodes sizes correctly. 
There are also limits to the range of values taking effect for `glPointSize` and `glLineWidth`
