### ISSUE TITLE
ctrl + (non numpad)-plus doesn’t work on win

### ISSUE THREAD

**Issue by Optiligence** [knossos-project/knossos#379]
plus key isn’t registered as Key_Plus

**Comment by Optiligence** [comment]
hyphen/minus worked, german layout on win10
works as expected on pc-jbuh
will check again later

**Comment by my-tien** [comment]
On Windows, evaluating the QKeyEvent manually for some reason results in `Qt::Key_BracketRight` for `Ctrl++`.
Using QActions witt Qt StandardKey `QKeySequence::ZoomIn` works as expected.

For the US keyboard the shortcut actually didn’t fire because Shift was always evaluated in isolation, discarding other keys pressed with it. This was fixed in a9b5938.
