### ISSUE TITLE
Bucket fill does not respect restricted movement area

### ISSUE THREAD

**Issue by adwanner** [knossos-project/knossos#412]
Outlining bucket fill regions at the boarder of the movement area without painting along the movement border results in whole ROI fill. Bucket fill should also respect the restricted movement area.

**Comment by Optiligence** [comment]
Bucket fill with middle click?

**Comment by adwanner** [comment]
yes

**Comment by Optiligence** [comment]
I guess the idea was to allow drawing the border outside the current FOV, potentially loading additional cubes. The FOV is smaller than the amount of loaded data due to overlap, which means wasted potential if its capped at viewport borders. 
You want the viewport as a border to the bucket fill? Because our feeling was that it wouldn’t be useful to have straight borders anywhere.

**Comment by Optiligence** [comment]
We also do have a dedicated movement area (independent of the current FOV)) whichld restrict the bucket fill.

**Comment by Optiligence** [comment]
^ ok, this isn’t the case, will be fixed.

**Comment by adwanner** [comment]
Use case: GT generation in  (small) subvolume that is defined by restricting the movement area (i.e. defining the movement area parameters min.x min.y min.z and max.x max.y max.z).

Below a series of screenshots illustrating the issue:
![screenshot01](https://cloud.githubusercontent.com/assets/17795672/26543791/8549b616-445f-11e7-8d0f-80bf627059bc.png)
![screenshot02](https://cloud.githubusercontent.com/assets/17795672/26543793/87026cfa-445f-11e7-9680-e2bdd7bfd04c.png)
![screenshot03](https://cloud.githubusercontent.com/assets/17795672/26543795/88dad512-445f-11e7-9fa3-e8f2afced903.png)

**Comment by adwanner** [comment]
Thanks a lot
