### ISSUE TITLE
Fails to run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [knossos-project/knossos#484]
Knossos fails to run on Ubuntu 14.04

Reference:
https://github.com/AppImage/appimage.github.io/pull/186

**Comment by probonopd** [comment]
https://github.com/knossos-project/knossos/blob/1d1b5ca75705155be5b3a9db96c80efeb20e5039/.travis.yml#L10

Please build on the oldest still-supported distribution release, e.g., Ubutnu 14.04. Otherwise your AppImage will fail to run on all still-supported distribution releases.

**Comment by Optiligence** [comment]
You’re funny. 

I’m gonna throw your
>if someone cares enough to send a PR

right back at you. 

The difference is, that this would – in addition to an initial working build environment – also have to be maintained by that _someone_. 

Canonical may still support 1404 (they are free to provide such a build environment), we don’t. 
1604 works – that’s 2 LTS releases. I will only put effort into supporting the latest LTS release (requiring users to update every 2 years seems reasonable to me), or more if there are any real users with a compelling reason. 

You may also (not) have noticed, that the glibc version check doesn’t matter in our case, because we ship it. 
It is actually Qt 5.12 that has a Linux 4.11 requirement now. (Unfortunately, this also means that it is not even possible to use Docker or Junest.)

PS: to be precise, it actually failed to run _everywhere_, because it didn’t create an AppImage at all anymore, just because it is _your_ opinion that it isn’t allowed to do so if it not also runs on 1404

**Comment by Optiligence** [comment]
>You are bundling glibc?

[yes](https://github.com/knossos-project/knossos/blob/1d1b5ca75705155be5b3a9db96c80efeb20e5039/installer/create_appimage.sh#L21)

>Qt 5.9 does not work for you?
the make file says [5.10](https://github.com/knossos-project/knossos/blob/1d1b5ca75705155be5b3a9db96c80efeb20e5039/CMakeLists.txt#L70)
but this may not even be up2date

I’m rather reluctant to let outdated systems dictate what features i can or cannot use. 
Especially if there is no user base. 

Also, fyi, you are talking about a nightly build, 
[v5.1](https://github.com/knossos-project/knossos/releases/tag/v5.1) may work on 1404 (i don’t have a vm at hand to test). It doesn’t work out of the box on 1204, but that could be alleviated by adding some libraries from there.

**Comment by probonopd** [comment]
> I’m rather reluctant to let outdated systems dictate what features i can or cannot use.

That's how backward compatibility works: You can only rely on what your users have, and your users can happen to run anything that is still-supported (by its vendor).
I would not call still-supported versions "outdated". 

By the way, Qt 5.9 is supported until 31.05.2020.

**Comment by Optiligence** [comment]
In the worst case they run something that isn’t even supported by anybody. 

But taking random support windows doesn’t point to anything. I could make a header only library and say it has 2 weeks support, would you point to that too? 
In fact, everybody can choose what they want to support themselves, so we support running KNOSSOS from 1604 onward, for now. 

And if there is _nobody_ that needs the current features _and_ is forced to work on an old system, it is simply a waste of time to maintain a stone-age build environment. 

You could argue that i should do my day2day work on such an old system, but i don’t want to live in the past, i want to live in the future. 

And _I_ would argue that it is less work to update an old user system (if you have policy, complain) than it is to maintain a custom distro that ships modern software.

**Comment by Optiligence** [comment]
We used to manually update compilers and libraries on travis (primarily by searching for PPAs). But that got tedious real fast. And, as i said, for not benefit.

**Comment by probonopd** [comment]
Better be tedious for _developers_ rather than being cumbersome for _users_, this is my mantra. How can you know that none of your users run an OS older than 16.04? (But hey, 16.04 will be the oldest still-supported LTS release in a couple of months, so the problem will solve itself really soon.)

**Comment by Optiligence** [comment]
It’s just a resource allocation question. We are happy to have a working CI at all. 

We encourage users to get in contact if something doesn’t work. It seems to work fine for all the users i’m aware of (at the research institutes and companies we collaborate with). 

And i don’t understand how you make the cuts so sharp on support window boundaries. It’s not like users get a notification: »Your Ubuntu doesn’t have support anymore, you have to update now!«. They will use it as long as they want – and _I_ don’t support _that_.
