### ISSUE TITLE
3D viewport: actual 3D? 

### ISSUE THREAD

**Issue by neworldemancer** [knossos-project/knossos#488]
Is there a foreseen option for the 3d view in the viewport with max. projections / other transfer functions?

**Comment by Optiligence** [comment]
In the nightly, there is a »combine consecutive slices« option in the layer dialog which does a min/max intensity projection. This is just in the slice viewports though, i don’t know what you envision to display in 3d with something like this. 

![image](https://user-images.githubusercontent.com/1899299/56314067-586a0100-6154-11e9-879e-094a12ca0576.png)

There is also the volume renderer which displays a voxel point cloud of segmentation data. 
This could be extended to work on thresholded raw data, but there are no plans atm. 
![image](https://user-images.githubusercontent.com/1899299/56314205-b0a10300-6154-11e9-87f8-47ac5dbaa03a.png)

The 3d viewport displays structures in the form of graphs (skeleton data) and meshes on the scale of the whole dataset whereas the only raw data to work with is situated around the current position. 
Creating something like segmentation/meshes that span the whole dataset is usually done offline and then only inspected and modified in K.

**Comment by neworldemancer** [comment]
The nightly seems pretty unstable... 
Generally existing functionality is almost what we need.. if that would work also in the "arbitrary" viewport :o))

I'd like to try to add something, yet currently experience difficulties with building components (PythonQt), and not sure if it KNOSSOS is generally build-able in setting I try (VS2013/QT5.6/Anaconda python 3.6). Whom could I contact for an advice on the default build configuration?

**Comment by Optiligence** [comment]
Please let us know in which circumstance it is unstable. 
We can look into adding that for the arb vp. Although i’m not sure it would be pleasant to use due to its performance impact (that’s why the xy-only flag exists). The arb vp is pretty much for tracing only, not inspection, and you wouldn’t want to set the nodes incorrectly while (seeing through). So i’m wondering why you want that functionality in the arb vp?

I’m not sure it’s possible to compile KNOSSOS with VS 2013 at all due to compliancy issues. It used to be impossible, but has gotten better, but i think VS 2013 doesn’t cut it. Qt 5.6 is definitely [too old](https://github.com/knossos-project/knossos/blob/e043e8928194746b045a2b0558cee4b378bc687e/CMakeLists.txt#L70). 
We build using [msys2](http://www.msys2.org/), you can check out [the build script](https://github.com/knossos-project/knossos/blob/master/ci/build_windows.sh). 
You can ask here or write an email at them team (knossosteam@gmail.com).

**Comment by neworldemancer** [comment]
Thanks, I see. msys2 build works.
I will play around and will do pull request once (if =P ) we reach smth reasonable.
