### ISSUE TITLE
Please make the python version (27) configurable

### ISSUE THREAD

**Issue by yurivict** [knossos-project/knossos#489]
https://github.com/knossos-project/knossos/blob/master/CMakeLists.txt#L86

python-27 is EOLed soon, and current python is 37.

**Comment by Optiligence** [comment]
As you point out it already is configurable. 
KNOSSOS itself is compatible with any version of Python (or PythonQt ftm). 
[PythonQt](https://github.com/knossos-project/PythonQt) can be built in Python3 mode via the `PythonQt_Python3` option.

**Comment by yurivict** [comment]
But ```CMakeLists.txt``` contains the hard-coded number: ```set(pythonqt Qt5Python27 ...```

**Comment by Optiligence** [comment]
it is a CACHE variable which means you can see and set/edit it

**Comment by yurivict** [comment]
I think you need to first determine the python version that is used, and the version in ```Qt5Python27``` should be derived from that. Otherwise they could be different which would be a mistake.

**Comment by Optiligence** [comment]
that is what the PythonQt build system [does](https://github.com/knossos-project/PythonQt/blob/4bf7da5adab4c6713360dd739322d66ddf1a28ac/CMakeLists.txt#L118)

What do you want to do?

**Comment by yurivict** [comment]
Yes, you should use ```${python_major}${python_minor}```.

> What do you want to do?

I am trying to create a FreeBSD port for ```knossos```, but this place attracted attention because it seems wrong that there's a need to hardcode the version.

**Comment by Optiligence** [comment]
To be able to get the Python version KNOSSOS would have to search for it and make that configurable too, which it has no business in, since this is fixed within the PythonQt build. What you set in KNOSSOS doesn’t matter if the PythonQt version is not available and PythonQt is also not necessarily built against the system-wide Python installation. 
That this says Qt5Python27 instead of simply PythonQt is due to the fact that PythonQt used to be stuck with Qt4, but we used Qt5 and decided to stay with Python2 back then, and Python’s minor releases are not backwards compatible (and may be installed alongside each other). 
Not all PythonQt are created equal. 
That the default is as it is, is also just our current deployment configuration. 

So you don’t want configurability but rather some kind of auto-detection for the Python version?

**Comment by yurivict** [comment]
Thank you for your explanation!

**Comment by Optiligence** [comment]
We’ll probably have a look at/change how the PythonQt targets work when we get the Python3 deployment over with. 

It’s certainly something that can be optimized somehow, thanks for bringing it up.
