### ISSUE TITLE
Changing viewport while drilling maintains drilling in the old viewport

### ISSUE THREAD

**Issue by orenshatz** [knossos-project/knossos#61]
1. Place the mouse in a viewport
2. Start drilling (press "F" constantly)
3. While drilling, move the mouse to another viewport
4. Look, drilling proceeds where it started instead of starting in the other viewport

This may be a problem when someone sees an interesting branch point or post-synapse and wants to follow it immediately without have to release the keyboard press.

**Comment by orenshatz** [comment]
Hi Alex. You can assign this to My-Tien if you want.

**Comment by Optiligence** [comment]
This is expected behavior. 
I even had 2 tracers telling me they especially liked how this is the case. 
It even is the default behavior of Qt/most other applications. 
The fact that K steals the keyboard focus on mouse move for the vps is kinda non-standard. 
(different keys for all axis, for example, would be independent of the currently hovered vp)

**Comment by orenshatz** [comment]
I'm not sure why you think this is expected or whether two tracers represent a sufficient sample size,
but for sure this has nothing to do with Qt or other apps, as the tracer (who probably doesn't know what Qt is) expects a custom-tailored user experience.
As far as I concern, keeping a single key and moving the mouse is the most rapid way of implementing the use-case I mentioned above.

**Comment by Optiligence** [comment]
viewports don’t steal keyboard focus on mouse hover anymore, which makes this impossible anyway
